config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/tpcchjslvqncmjcxkbcpmese' => 'tpcchjslvqncmjcxkbcpmese#index'
  get '/tpcchjslvqncmjcxkbcpmese/all'
  get '/tpcchjslvqncmjcxkbcpmese/show'
  post 'tpcchjslvqncmjcxkbcpmese/create'
  post 'tpcchjslvqncmjcxkbcpmese/delete'
  post 'tpcchjslvqncmjcxkbcpmese/up'
  post 'tpcchjslvqncmjcxkbcpmese/down'

  get ':id' => 'home#quiz'
  post 'answer/:id/:question/:answer' => 'home#answer'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
    belongs_to :user
    belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
    has_attached_file :pic
    validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/
    has_many :answers
    before_destroy :purge

    def prev
        Question.find_by_order(self.order - 1)
    end

    def next
        Question.find_by_order(self.order + 1)
    end

    def purge
        self.answers.all.destroy_all
    end

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def quiz
        @user = User.find_by_password(params['id'])
        @questions = Question.all.sort_by { |q| q.order }
    end

    def answer
        if a = User.find(params['id']).answers.find_by_question_id(params['question'])
            if a.choice != params['answer']
                a.delete
                Question.find(params['question']).answers.new(user_id: params['id'], choice: params['answer']).save
            end
        else
            Question.find(params['question']).answers.new(user_id: params['id'], choice: params['answer']).save
        end

        respond_to do |format|
            format.js { render 'home/answer.js.erb', :layout => false }
        end
    end

end

app/controllers/tpcchjslvqncmjcxkbcpmese_controller.rb
class TpcchjslvqncmjcxkbcpmeseController < ApplicationController

    def index
        @questions = Question.all.sort_by { |q| q.order }
    end

    def create
        question = Question.new(text: params["text"])
        if params["a"] or params[b] or params[c] or params[d]
            question.multiple_choice = true
            question.a = params["a"] if params["a"]
            question.b = params["b"] if params["b"]
            question.c = params["c"] if params["c"]
            question.d = params["d"] if params["d"]
        end
        if params['file']
            question.pic = params['file']
        end
        question.order = Question.all.size > 0 ? Question.all.pluck(:order).max + 1 : 1
        question.save

        redirect_to action: 'index'
    end

    def delete
        question = Question.find(params['question'])
        questions = []
        Question.all.each do |q|
            if q.order > question.order
                q.update_attribute(:order, q.order - 1)
            end
        end
        question.destroy

        redirect_to action: 'index'
    end

    def up
        q = Question.find(params['question'])
        if q.prev
            q.prev.update_attribute(:order, q.order)
            q.update_attribute(:order, q.order - 1)
        end

        redirect_to action: 'index'
    end

    def down
        q = Question.find(params['question'])
        if q.next
            q.next.update_attribute(:order, q.order)
            q.update_attribute(:order, q.order + 1)
        end

        redirect_to action: 'index'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tpcchjslvqncmjcxkbcpmese_helper.rb
module TpcchjslvqncmjcxkbcpmeseHelper
end

app/views/home/index.html.haml
HELLO

app/views/home/quiz.html.haml
QUIZ
%p

- @questions.each do |question|
    = question.order.to_s + '.'
    = question.text
    %br
    %li
        %ul
            - if question.pic.exists?
                = image_tag question.pic.url, size: '100x100'
    - if question.multiple_choice
        / get answer here use to place select tag
        - if a = User.find(@user.id).answers.find_by_question_id(question.id)
            - answer = a.choice
        - else
            - answer = 'z'

        %li
            - if question.a != ""
                %ul
                    = radio_button_tag question.id.to_s, 'a', answer == 'a', onclick: "choose('#{@user.id}' , '#{question.id}', 'a')"
                    A.
                    = question.a
            - if question.b != ""
                %ul
                    = radio_button_tag question.id.to_s, 'b', answer == 'b', onclick: "choose('#{@user.id}' , '#{question.id}', 'b')"
                    B. 
                    = question.b
            - if question.c != ""
                %ul
                    = radio_button_tag question.id.to_s, 'c', answer == 'c', onclick: "choose('#{@user.id}' , '#{question.id}', 'c')"
                    C.
                    = question.c
            - if question.d != ""
                %ul
                    = radio_button_tag question.id.to_s, 'd', answer == 'd', onclick: "choose('#{@user.id}' , '#{question.id}', 'd')"
                    D.
                    = question.d
    %p
    %br
    %br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spanglish</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tpcchjslvqncmjcxkbcpmese/all.html.haml
All users
%p
- User.all.each do |user|
    = user.id
    = link_to user.password, "/" + user.password

app/views/tpcchjslvqncmjcxkbcpmese/index.html.haml
ADD QUESTION
%div
    = form_tag 'tpcchjslvqncmjcxkbcpmese/create', multipart: true, method: :post do 
        = text_area_tag "text", nil, class: 'my-area'

        %p
        = label_tag "pic"
        = file_field_tag "file"

        %p
        Options
        %p
        = label_tag "A"
        = text_field_tag "a", nil, class: 'my-input'
        %p
        = label_tag "B"
        = text_field_tag "b", nil, class: 'my-input'
        %p
        = label_tag "C"
        = text_field_tag "c", nil, class: 'my-input'
        %p
        = label_tag "D"
        = text_field_tag "d", nil, class: 'my-input'


        %p
        = submit_tag "Submit", :class => 'btn btn-default'

%p
QUESTIONS
%p
- @questions.each do |question|
    = question.order
    = question.text
    = link_to 'up', tpcchjslvqncmjcxkbcpmese_up_path(question: question), method: 'post'
    = link_to 'down', tpcchjslvqncmjcxkbcpmese_down_path(question: question), method: 'post'
    = link_to 'del', tpcchjslvqncmjcxkbcpmese_delete_path(question: question), method: 'post'
    %br
    - if question.pic.exists?
        = image_tag question.pic.url, size: '100x100'
    %br
    - if question.multiple_choice
        %li
            - if question.a
                %ul
                    A.
                    = question.a
            - if question.b
                %ul
                    B. 
                    = question.b
            - if question.b
                %ul
                    C.
                    = question.c
            - if question.b
                %ul
                    D.
                    = question.d
    %p